name: agrixona24
description: An agricultural professional community app
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.16.0
  cupertino_icons: ^1.0.2
  animated_login: ^1.7.2
  flutter_login: ^4.2.1
  flutter_svg: ^2.0.9
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.3
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  video_player: ^2.8.2
  share: ^2.0.4
  video_compress: ^3.1.2
  flutter_image_compress: ^2.1.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/agrixona_connect.png
    - assets/images/agrixona_icon.png
    - assets/images/search.svg
    - assets/images/agrixona.png
    - assets/images/english.png
    - assets/images/france.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
