// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA40YxokTUxedGsOZuENl-1LHmyowQyzrw',
    appId: '1:790129469615:web:75a20bf4ad40cb7dc00c5a',
    messagingSenderId: '790129469615',
    projectId: 'agrixona24',
    authDomain: 'agrixona24.firebaseapp.com',
    storageBucket: 'agrixona24.appspot.com',
    measurementId: 'G-9YN6J5GG3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ES2GYE_s_t5TI9YGKIQb02aBHpeNbtU',
    appId: '1:790129469615:android:d016e5c049e0e253c00c5a',
    messagingSenderId: '790129469615',
    projectId: 'agrixona24',
    storageBucket: 'agrixona24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2od0z19x8wfV-PCJzumWeqxJxsL8w1oM',
    appId: '1:790129469615:ios:9bcd0810376d1211c00c5a',
    messagingSenderId: '790129469615',
    projectId: 'agrixona24',
    storageBucket: 'agrixona24.appspot.com',
    iosBundleId: 'com.agrinodi.agrixona24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2od0z19x8wfV-PCJzumWeqxJxsL8w1oM',
    appId: '1:790129469615:ios:a0ac903aa83b54b7c00c5a',
    messagingSenderId: '790129469615',
    projectId: 'agrixona24',
    storageBucket: 'agrixona24.appspot.com',
    iosBundleId: 'com.agrinodi.agrixona24.RunnerTests',
  );
}
